server:
  port: 8083

spring:
  application:
    name: quote-graph

dgs:
  graphql:
    path: /graphql
    schema-locations: classpath:graphql/**
  federation:
    enabled: true

logging:
  level:
    com.cnbc.quotegraph: DEBUG